# Application
application:
  auth:
    username: ${USERNAME_AUTH:admin}
    password: ${PASSWORD_AUTH:p4sswd}
    role: ${ROLE_AUTH:ADMIN}
  source:
    back-end: ${REPOSITORY_URL_BACKEND:https://github.com/marrodrigues/mrit-pessoas-api}
    front-end: ${REPOSITORY_URL_FRONTEND:https://github.com/marrodrigues/mrit-pessoas}

# Endpoints
endpoints:
  restart:
    enabled: true

# Server
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types:
      - application/json
    min-response-size: 10240

# Spring
spring:
  data:
    mongodb:
      uri: ${MONGO_STRING_CONNECTION:mongodb+srv://desafio-pessoa:p4sswd@cluster0.ijyny.mongodb.net/desafio-pessoa?retryWrites=true&w=majority}

# SpringFox
springfox:
  documentation:
    open-api:
      v3:
        path: '/api-docs'